title: JoshAtticus Blog
author: JoshAtticus
description: > # this means to ignore newlines until "baseurl:"
  Official JoshAtticus jekyll blog. Thanks to lankybox02 on Github for the domain!
# social links
github_username:  JoshAtticus # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
